### ISSUE TITLE
Créer les headers pour chaque Class commentaire requis par le professeur

### ISSUE THREAD

**Issue by ocontant** [ocontant/INF731-TP2#12]
Exemple: 
/// <summary>
    /// Auteur: Olivier Contant
    /// Auteur: Amadou Yaya Kane
    /// Date:  2016-09-29
    /// Remise: 2016-10-12
    /// 
    /// Nom Projet: TP1
    /// Description: 
    /// Produire la moyenne des notes d’un groupe de plusieurs étudiants.
    ///     - Produire un rapport fichier avec les informations suivantes:
    ///         + Une entête
    ///             -------------------------------------------------------------------------
    ///             Résultats du groupe B-2994 - fichier lu Test1.txt
    ///             par Archambault, Luc et Laliberté, Denis
    ///             -------------------------------------------------------------------------
    ///         + Liste des étudiants ordonnée croissant basé sur le prénom; Affiche: 
    ///             ++ Nom, Prénom, Note
    ///         + Liste des étudiants ordonnée décroissant basé sur la note; affiche:
    ///             ++ Nom, Prénom, Note
    ///         + Indiquer la moyenne, la médiane, la note la plus haute et la note la plus basse; Affiche:
    ///             ++ Moyenne
    ///             ++ Médiane
    ///             ++ Nom, Prénom, Note la plus haute
    ///             ++ Nom, Prénom, Note la plus basse
    ///         
    /// Fichier d'entré:  test_data.csv
    /// Fichier de sorti: Journal-<nom_fichier_entré>
    /// 
    /// Fichiers Sources: 
    ///   - Program.cs  Programme Main
    ///   - Groupe.cs   Class gérant les groupes d'étudiant
    ///   - Etudiant.cs Class gérant les étudiants
    ///   - GestionFichier.cs Classe gérant la lecture et l'écriture dans un fichier
    ///   - GestionMessage.cs Class qui gère les messages 
    /// </summary>

**Comment by ocontant** [comment]
Je voulais au départ partager qui avait codé quoi initialement.  Mais comme on a tous participé ici et là, je pense qu'on devrait simplement mettre tous les noms dans chacune des classes. 

On pourrait rajouter dans la documentation des méthodes une ligne qui défini qui a codé la méthode. (peut avoir plus qu'un nom).

**Comment by ocontant** [comment]
Askoum, je t'ai mis leader sur cet issue.  J'aimerias que tu fasses le suivit avec nous pour que tout soit bien documenté et faire le suivit avec ceux qui ont oublié de documenté leurs méthodes.

**Comment by ocontant** [comment]
/// <INF731-TP2>
///     <auteurs>
///         <auteur> Olivier Contant <email> olivier.contant@USherbrooke.ca </email></auteur>
///     </auteurs>
/// 
///     <summary>
///         Classe définissant les comptes de type Flexible de la banque.
///     </summary>
///     
///     <méthodes>
///         <méthode> 
///             <Nom> ParseCSV(string ligne) </Nom>
///             <Description> Lit une ligne csv et créer un Array de string </Description>
///         </méthode>
///         <méthode>
///             <Nom> loadClients(String cheminFichier) </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///         <méthode>
///             <Nom> </Nom>
///             <Description> </Description>
///         </méthode>
///     </méthodes>
/// </INF731-TP2>

**Comment by askoum** [comment]
Issu #12 Headers comments : resolve
