### ISSUE TITLE
CompteÉpargne.cs [ Propriété SoldeMoyen ]  Validation pour le set

### ISSUE THREAD

**Issue by ocontant** [ocontant/INF731-TP2#17]
Est-ce que le solde moyen peut-être inférieur à 0 ?

**Comment by sorydiane** [comment]
On travaille sur ca actuellement

**Comment by sorydiane** [comment]
L'exception est implemente mais pas encore teste. On est entrain de voir comment tester la methode     AjouterIntérêt() du calcul de soldeMoyen dans le program.cs

**Comment by askoum** [comment]
Issue Fixed
